---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: 了解 NetApp Console 本機部署中各項功能和資料服務的最新變更。 
---
= NetApp Console 本地部署的最新變更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解 NetApp Console 本機部署功能和資料服務的最新變更。



[[10-august-2026]]
== 2026年8月10日

未解析的指令位於 <stdin> - include::_include/console-local.adoc[] :leveloffset: +1



[[introducing-netapp-console-local-deployment]]
=== 介紹 NetApp Console 本地部署

https://docs.netapp.com/us-en/console-local/netapp-console-local.html["學習 NetApp Console 本機部署"]。



[[backup-and-recovery]]
=== 備份與還原



==== 一般 NetApp Backup and Recovery 增強功能

* *支援 NetApp Console 本機部署*：此 NetApp Backup and Recovery 版本以預覽狀態支援 NetApp Console 本機部署。
* *90 天作業保留*：Backup and Recovery 現在會在作業監視器中保留作業資訊 90 天。




==== VMware 工作負載增強功能

在此版本中、VMware 工作負載引進了以下增強功能：

* *SAN VM 還原至備用位置支援*：您現在可以將基於 SAN 的 VM 備份還原至備用位置。
* *支援批次刪除備份*：現在可以一次刪除多個備份。


有關保護 VMware 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保護 VMware 工作負載概述"]。



==== Oracle Database 工作負載增強功能

在此版本中、Oracle Database 工作負載引進下列增強功能：

* *可插拔資料庫 （PDB） 還原與 Clone*：Backup and Recovery for NetApp Console 服務現在支援還原與複製可插拔資料庫。


有關保護 Oracle Database 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["保護 Oracle Database 工作負載概述"]。



==== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *預覽版支援氣隙資源*：如果在 NetApp Console 本機部署中執行 NetApp Backup and Recovery，您可以探索、保護和還原氣隙 Kubernetes 資源。此功能在此版本中為預覽功能。


有關保護 Kubernetes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保護 Kubernetes 工作負載概述"]。



==== ONTAP Volumes 工作負載增強功能

在此版本中，ONTAP Volumes 工作負載引入了以下增強功能：

* *優先執行還原作業而非備份作業*：現在，在還原虛擬機器或檔案時，您可以優先執行還原作業而非備份作業。
* *無需啟動 Backup and Recovery 即可探索 ONTAP 系統和磁碟區*：您現在無需啟動 Backup and Recovery 即可探索系統和磁碟區。


有關保護 ONTAP Volumes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["保護 ONTAP Volumes 工作負載概述"]。



[[13-july-2026]]
== 2026年7月13日



[[backup-and-recovery]]
=== 備份與還原



==== 增強對所有工作負載的多儲存貯體支援

NetApp Backup and Recovery 現在支援保護系統中多達 100 個儲存桶（跨不同雲端供應商）的工作負載。每個系統支援超過 6 個儲存桶需要 ONTAP 9.19.1 或更新版本。

有關 NetApp Backup and Recovery 的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["了解 NetApp Backup and Recovery"]。



[[15-june-2026]]
== 2026 年 6 月 15 日



[[backup-and-recovery]]
=== 備份與還原



==== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *Trident Protect 26.06*：此版本包含 Trident Protect 26.06。
* *恢復期間跳過應用程式建立*：現在您可以在復原作業期間跳過自動建立應用程式自訂資源物件。這樣可以減少應用程式清單中不必要的條目。
* *還原 VM 持久性磁碟區請求*：還原 VM 型應用程式時，現在可以還原個別持久性磁碟區請求，而無需還原整個虛擬機器，當特定磁碟或磁碟區受到損毀或資料遺失影響時，可加快復原速度。
* *作業監控改進*：作業監控功能現已增強，可更清楚顯示 Kubernetes 保護作業的狀態。您可以查看作業和子作業的詳細狀態資訊，以及每個作業使用的目標儲存。


有關保護 Kubernetes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保護 Kubernetes 工作負載概述"]。



[[08-june-2026]]
== 2026 年 6 月 08 日



[[backup-and-recovery]]
=== 備份與還原



==== ONTAP Volumes 工作負載增強功能

在此版本中，ONTAP Volumes 工作負載引入了以下增強功能：

*支援 S3 相容的雲端儲存*：NetApp Backup and Recovery for Volumes 工作負載現在支援備份到 S3 相容的雲端儲存。

有關保護 ONTAP Volumes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["保護 ONTAP Volumes 工作負載概述"]。



==== Hyper-V 工作負載增強功能

在此版本中、Hyper-V 工作負載引入了以下增強功能：

* *將檔案和資料夾還原到客體 VM 的功能改進*：現在您可以將主要或次要儲存設備上快照中的檔案和資料夾還原到客體 Windows VM。CIFS 和 SAN VM 現在支援此功能。
* *保護群組現在使用主機時區排程*：保護群組現在使用 Hyper-V 主機的時區。在引入主機時區排程功能之前建立的保護群組將繼續使用其先前設定的時間（通常為 UTC）。若要將這些保護群組更新為使用 Hyper-V 主機時區，您必須重新建立排程。如需詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["建立和管理 Hyper-V 工作負載的保護群組"]。


有關保護 Hyper-V 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["保護 Hyper-V 工作負載概述"]。



==== VMware 工作負載增強功能

在此版本中、VMware 工作負載引進下列增強功能：

* *保護群組現在使用主機時區排程*：保護群組現在使用宿主 VMware vCenter 伺服器的時區。在引入主機時區排程功能之前建立的保護群組將繼續使用先前設定的時區（通常為 UTC）運作。若要使用 vCenter 時區，您必須重新建立排程。如需詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["建立並管理 VMware 工作負載的保護群組"]。


有關保護 VMware 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保護 VMware 工作負載概述"]。
