---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: 了解 NetApp Console 本機部署中各項功能和資料服務的最新變更。 
---
= NetApp Console 本地部署的最新變更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解 NetApp Console 本機部署功能和資料服務的最新變更。



[[28-september-2026]]
== 2026 年 9 月 28 日



[[backup-and-recovery]]
=== 備份與還原



==== 通用 NetApp Backup and Recovery 增強功能

在此版本中，KVM、Hyper-V 和 VMware 工作負載引入了以下增強功能：

*主控台角色型存取控制（RBAC）支援*：Hyper-V、KVM 和 VMware 工作負載現在支援 RBAC 的 NetApp Console 架構，可讓您管理對個別 Hyper-V、KVM 或 VMware 主機的存取。

https://docs.netapp.com/us-en/data-services-backup-recovery/br-rbac-setup.html["深入了解在 NetApp Backup and Recovery 中使用 RBAC 的相關資訊"]。



==== ONTAP Volumes 工作負載增強

在此版本中，ONTAP Volumes 工作負載引入了以下預覽增強功能：

*Cloud Volumes ONTAP Azure Entra ID 支援*：如果您不想使用儲存設備帳戶存取金鑰進行 Azure 驗證，現在可以對 Azure 物件儲存儲存區組態使用 Microsoft Entra ID 驗證。此選項適用於執行 ONTAP 9.16.1 或更新版本的 Azure 系統中的 Cloud Volumes ONTAP。

有關保護 ONTAP Volumes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["了解使用 NetApp Backup and Recovery 的 ONTAP Volume 保護"]。



==== VMware 工作負載增強

在此版本中、VMware 工作負載引進下列增強功能：

*Google Cloud NetApp Volumes Flex Unified 支援*：適用於 VMware 工作負載的 NetApp Backup and Recovery 現已支援 Google Cloud NetApp Volumes 的 Flex Unified 服務層級。Flex Unified 僅在 ONTAP 模式下支援。

有關保護 VMware 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["使用 NetApp Backup and Recovery 保護 VMware 工作負載"]。



[[21-september-2026]]
== 2026 年 9 月 21 日



[[backup-and-recovery]]
=== 備份與還原



==== ONTAP Volumes 工作負載增強功能

在此版本中，ONTAP Volumes 工作負載引入了以下預覽增強功能：

* *改進對隔離站台的支援*：適用於隔離站台的 NetApp Backup and Recovery 現在提供與 NetApp Backup and Recovery 相同的 ONTAP Volumes 資料保護功能。此增強功能包括更新的備份、還原和作業管理服務以及新的中繼資料資料庫。升級期間，現有資料庫資料將保留並自動移轉。升級後，審查稽核記錄以驗證移轉是否成功完成。適用於隔離站台的 NetApp Backup and Recovery 僅支援 ONTAP Volumes 工作負載。
* *取消 Volume 還原作業*：現在可以從作業監控頁面取消後續的 ONTAP Volume 還原作業，更容易管理長時間運作或運作緩慢的作業。
* *改進的 Volume 索引狀態報告*：ONTAP Volumes 儀表板現在透過針對不符合索引條件的 Volume 和快照複本引入 `Not Applicable`狀態，更準確地報告索引狀態。此 `Not Indexed`狀態現在保留給等待索引的 Volume，且 Volume 詳細資料現在會顯示每個快照的索引狀態，並帶有懸停文字來解釋為何 Volume 或快照複本不會被索引。
* *NetApp AFX 支援*：您現在可以保護託管在 2 節點和 4 節點 NetApp AFX 叢集上的 Volume。


有關保護 ONTAP Volumes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["了解使用 NetApp Backup and Recovery 的 ONTAP Volume 保護"]。



==== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *Trident Protect 26.09*：此版本包含 Trident Protect 26.09。
* *叢集與命名空間精細度的角色型存取控制（RBAC）*：在 Kubernetes 叢集探索期間，您可以透過選取要與新叢集建立關聯的專案或資料夾，來控制對資源的存取。您也可以註冊特定的命名空間以進行存取控制。這可在叢集或命名空間層級實現更精細的存取控制。
* *還原檔案和資料夾*：您現在可以從基於 Kubernetes VM 的應用程式備份中還原或下載特定的檔案和資料夾。


有關保護 Kubernetes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保護 Kubernetes 工作負載"]。



[[16-september-2026]]
== 2026 年 9 月 16 日



[[backup-and-recovery]]
=== 備份與還原



==== 通用 NetApp Backup and Recovery 增強功能

在此版本中，KVM、Hyper-V 和 VMware 工作負載引入了以下增強功能：

*虛擬機器主機探索期間的憑證選擇*：當您探索 KVM、Hyper-V 或 VMware 主機時，現在可以使用已新增至 Backup and Recovery 的憑證。



==== Hyper-V 工作負載增強

在此版本中，Hyper-V 工作負載引入了以下增強功能：

*虛擬機器的跨磁碟保護*：對於 CIFS 配置，Backup and Recovery 現在支援保護保護群組中每個虛擬機器所連接的每個磁碟。這包括分佈在多個 ONTAP 磁碟區或 ONTAP 儲存設備系統上的檔案（跨磁碟），以及僅限於單一位置的檔案。

有關保護 Hyper-V 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保護 Hyper-V 工作負載"]。



==== ONTAP Volumes 工作負載增強

在此版本中，ONTAP Volumes 工作負載引入了以下預覽增強功能：

*每日備份資料傳輸報告*： NetApp Backup and Recovery for Volumes 現已在「報告」標籤下新增每日備份資料傳輸報告，讓您獲得整個環境中每日備份和複寫資料傳輸活動的可見度。您可以產生整個帳戶或選定儲存設備系統的報告，按日期範圍和保護類型進行篩選，並將結果下載為 CSV 檔案。

有關保護 ONTAP Volumes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["了解使用 NetApp Backup and Recovery 的 ONTAP Volume 保護"]。



[[17-august-2026]]
== 2026年8月17日



[[backup-and-recovery]]
=== 備份與還原



==== Hyper-V 工作負載增強功能

在此版本中，Hyper-V 工作負載引入了以下增強功能：

*將物件儲存備份還原到備用位置*：您現在可以將 Hyper-V 虛擬機器、檔案和資料夾從物件存放區還原到備用儲存設備位置。

有關保護 Hyper-V 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保護 Hyper-V 工作負載"]。



==== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *Trident Protect 26.08*：此版本包含 Trident Protect 26.08。
* *備份重試*：您現在可以在 Kubernetes 保護原則的進階設定中啟用備份重試，並設定重試次數和重試間隔。
* *部分備份成功*：您現在可以在 Kubernetes 保護原則中設定進階設定，以便在個別資源發生故障時繼續備份，從而使備份作業部分成功完成。這樣，即使某些資源在備份作業期間發生故障，您仍然可以還原已備份的資源。
* *損毀狀況一致與 VM 一致備份*：Backup and Recovery for NetApp Console 服務現在支援設定保護原則，以建立損毀狀況一致或 VM 一致的備份或快照。您還可以自訂在保護作業期間執行 VM 凍結的方式。
* *Console 代理程式 IP 位址變更時重新連接 Kubernetes 叢集*：Backup and Recovery for NetApp Console 服務現在可讓您在代理程式的 IP 位址變更時，將叢集重新連接至其 Console 代理程式。
* *將叢集移轉至新的 Console 代理程式*：Backup and Recovery for NetApp Console 服務現在可讓您在原始代理程式失敗或被刪除時，將叢集移轉至新的 Console 代理程式，以確保應用程式保護不中斷。


有關保護 Kubernetes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保護 Kubernetes 工作負載"]。



==== Oracle 資料庫工作負載增強

在此版本中、Oracle Database 工作負載引進下列增強功能：

* *可插拔資料庫 (PDB) 還原*：現在可以還原單一可插拔資料庫 (PDB) 和 PDB 表空間，包括時間點恢復。
* *可插拔資料庫 (PDB) Clone*：現在可以將單一 PDB Clone 到現有的目標 Container 資料庫 （CDB） 中，並且可以選擇在 Clone 整個 Container 資料庫時排除 PDB。


有關保護 Oracle Database 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保護 Oracle 資料庫工作負載"]。



[[10-august-2026]]
== 2026年8月10日



[[netapp-console-local-deployment]]
=== NetApp Console 本地部署



==== 介紹 NetApp Console 本地部署

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["學習 NetApp Console 本機部署"]。

https://docs.netapp.com/us-en/console-local/console-differences.html["了解 NetApp Console 本地部署、NetApp Console SaaS 和私有模式之間的差異"]。



[[backup-and-recovery]]
=== 備份與還原



==== 一般 NetApp Backup and Recovery 增強功能

* *支援 NetApp Console 本機部署*：此 NetApp Backup and Recovery 版本以預覽狀態支援 NetApp Console 本機部署。
* *90 天作業保留*：Backup and Recovery 現在會在作業監視器中保留作業資訊 90 天。




==== VMware 工作負載增強功能

在此版本中、VMware 工作負載引進了以下增強功能：

* *SAN VM 還原至備用位置支援*：您現在可以將基於 SAN 的 VM 備份還原至備用位置。
* *支援批次刪除備份*：現在可以一次刪除多個備份。


有關保護 VMware 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保護 VMware 工作負載概述"]。



==== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *預覽版支援氣隙資源*：如果在 NetApp Console 本機部署中執行 NetApp Backup and Recovery，您可以探索、保護和還原氣隙 Kubernetes 資源。此功能在此版本中為預覽功能。


有關保護 Kubernetes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保護 Kubernetes 工作負載概述"]。



==== ONTAP Volumes 工作負載增強功能

在此版本中，ONTAP Volumes 工作負載引入了以下增強功能：

* *優先執行還原作業而非備份*：現在，在還原磁碟區、檔案或資料夾時，您可以優先執行還原作業而非備份作業。
* *無需啟動 Backup and Recovery 即可探索 ONTAP 系統和磁碟區*：您現在無需啟動 Backup and Recovery 即可探索系統和磁碟區。


有關保護 ONTAP Volumes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["保護 ONTAP Volumes 工作負載概述"]。



[[13-july-2026]]
== 2026年7月13日



[[backup-and-recovery]]
=== 備份與還原



==== 增強對所有工作負載的多儲存貯體支援

NetApp Backup and Recovery 現在支援保護系統中多達 100 個儲存桶（跨不同雲端供應商）的工作負載。每個系統支援超過 6 個儲存桶需要 ONTAP 9.19.1 或更新版本。

有關 NetApp Backup and Recovery 的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["了解 NetApp Backup and Recovery"]。
